/*
 * This file is protected by Copyright. Please refer to the COPYRIGHT file 
 * distributed with this source distribution.
 * 
 * This file is part of REDHAWK core.
 * 
 * REDHAWK core is free software: you can redistribute it and/or modify it 
 * under the terms of the GNU Lesser General Public License as published by the 
 * Free Software Foundation, either version 3 of the License, or (at your 
 * option) any later version.
 * 
 * REDHAWK core is distributed in the hope that it will be useful, but WITHOUT 
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License 
 * for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License 
 * along with this program.  If not, see http://www.gnu.org/licenses/.
 */

#ifndef _NEGOTIABLE_PORT_IDL_
#define _NEGOTIABLE_PORT_IDL_

#include "ossie/CF/QueryablePort.idl"

module ExtendedCF {

    exception NegotiationError {
       string msg;
    };

    struct TransportInfo {
        string transportType;
        CF::Properties transportProperties;
    };

    typedef sequence<TransportInfo> TransportInfoSequence;

    interface NegotiablePort {
        readonly attribute TransportInfoSequence supportedTransports;
    };

    struct ConnectionStatus {
        string connectionId;
        Object port;
        boolean alive;
        string transportType;
        CF::Properties transportInfo;
    };

    typedef sequence<ConnectionStatus> ConnectionStatusSequence;

    interface NegotiableUsesPort : ExtendedCF::QueryablePort, NegotiablePort {
        readonly attribute ConnectionStatusSequence connectionStatus;
    };

    struct NegotiationResult {
        string transportId;
        CF::Properties properties;
    };

    interface NegotiableProvidesPort : NegotiablePort {
        NegotiationResult negotiateTransport(in string transportType, in CF::Properties transportProperties)
            raises (ExtendedCF::NegotiationError);

        void disconnectTransport(in string transportId)
            raises (ExtendedCF::NegotiationError);
    };
};

#endif
