/*
 * This file is protected by Copyright. Please refer to the COPYRIGHT file 
 * distributed with this source distribution.
 * 
 * This file is part of REDHAWK core.
 * 
 * REDHAWK core is free software: you can redistribute it and/or modify it 
 * under the terms of the GNU Lesser General Public License as published by the 
 * Free Software Foundation, either version 3 of the License, or (at your 
 * option) any later version.
 * 
 * REDHAWK core is distributed in the hope that it will be useful, but WITHOUT 
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License 
 * for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License 
 * along with this program.  If not, see http://www.gnu.org/licenses/.
 */

#ifndef __WELLKNOWN_PROPERTIES
#define __WELLKNOWN_PROPERTIES

module ExtendedCF {
    module WKP {
        const string DEVICEKIND          = "DCE:cdc5ee18-7ceb-4ae6-bf4c-31f983179b4d";
        const string DEVICEMODEL         = "DCE:0f99b2e4-9903-4631-9846-ff349d18ecfb";
        const string OS_NAME             = "DCE:4a23ad60-0b25-4121-a630-68803a498f75";
        const string OS_VERSION          = "DCE:0f3a9a37-a342-43d8-9b7f-78dc6da74192";
        const string PROCESSOR_NAME      = "DCE:fefb9c66-d14a-438d-ad59-2cfd1adb272b";
        const string AWARE_APPLICATION = "AWARE_APPLICATION";
    };
};
#endif
