#!/bin/bash
#
# Runs relative to frontend project
#

# can't use relative path for subdir's
# must get actual path so that subdir's use the correct path
frontend_top=$(cd ../../..;pwd)
frontend_libsrc_top=$frontend_top/libsrc
export LD_LIBRARY_PATH=$frontend_libsrc_top/.libs:$frontend_top/.libs:$frontend_top/jni/.libs:${LD_LIBRARY_PATH}
export PYTHONPATH=$frontend_libsrc_top/python:${PYTHONPATH}
export CLASSPATH=${frontend_libsrc_top}/frontend.jar:${frontend_top}/frontendInterfaces.jar:${CLASSPATH}

# Limit the number of threads Java uses for the garbage collector to avoid
# misleading Java "out of memory" errors that in all actuality  appear to be
# due to hitting the per-user process limit
export _JAVA_OPTIONS="-XX:ParallelGCThreads=1"

with_xunit=
pproc=
if [ $# -gt 0 ];
then
   if [ "-with-xunit" == "${1##[-+]}" ];
   then
       with_xunit="--with-xunit"
       shift
   fi
fi

#
#  Run Python Sandbox based testing (this is a placeholder, there are none right now)
#

if [ $# -gt 0 ]
then
    # run an associated test script
    python  $*
    exit
else
    if test -n "$(find . -maxdepth 1 -name 'test_*.py' -print -quit)"
    then
        for pt in test_*.py ; do
            python $pt
        done
    fi
fi

#
#  Run Java unit tests
#
cd java
./runtests $with_xunit
cd -

#
#  Run C++ unit tests
#
cd cpp
./runtests $with_xunit
cd -

#
# Run Python unit tests with XML output
#
(cd python && ./runtests.py -x)
