# This component exists solely to test that an empty directory gets copied to
# the device's cache. However, git does not track directories, and adding a
# file to the directory defeats the purpose. This makefile works around the
# problem.

all: cmd_dir/tmp

cmd_dir/tmp:
	mkdir $@

install:

distclean:

clean:

