#!/bin/bash
#
# Runs relative to bulkio project
#

# can't use relative path for subdir's
# must get actual path so that subdir's use the correct path
bulkio_top=$(cd ../../..;pwd)
bulkio_libsrc_top=$bulkio_top/libsrc
export LD_LIBRARY_PATH=$bulkio_libsrc_top/.libs:$bulkio_top/.libs:$bulkio_top/jni/.libs:${LD_LIBRARY_PATH}
export PYTHONPATH=$bulkio_libsrc_top/python:${PYTHONPATH}
export CLASSPATH=${bulkio_libsrc_top}/bulkio.jar:${bulkio_top}/BULKIOInterfaces.jar:${CLASSPATH}

# Limit the number of threads Java uses for the garbage collector to avoid
# misleading Java "out of memory" errors that in all actuality  appear to be
# due to hitting the per-user process limit
export _JAVA_OPTIONS="-XX:ParallelGCThreads=1"

#
#  Run Python Sandbox based testing..
#

if [ $# -gt 0 ]
then
    # run an associated test script
    python  $*
    exit
else
    for pt in test_*.py ; do
       python $pt
    done
fi

#
#  Run Java unit tests
#
if command -v ant 2>/dev/null
then
    ant -f java/build.xml
else
    make -C java
fi


#
#  Run C++ unit tests
#
cd cpp
./runtests
cd -

#
# Run Python unit tests with XML output
#
# NOTE: virtualenv aliases python in the shell, so it's necessary to explicitly
# run runtests.py via python
(cd python && python ./runtests.py -x)

#
#  Run Large Packet Size Test
#
#
cd ../components/TestLargePush/tests/
./test_TestLargePush.py
cd -

#
#  Run Attachable/Multiout Test
#
#
cd ../components/multiout_attachable/tests/
./test_multiout_attachable.py
cd -

#
#  Run Oversized frame data Test
#
#
cd ../components/Oversized_framedata/tests/
./test_Oversized_framedata.py
cd -

#
#  Run port lock Test
#
#
cd ../components/src/tests/
./test_src.py
cd -

#  Run jni reference resolution
#
#
cd ../devices/dev_src/tests/
python test_dev_src.py
cd -
