/*
 * This file is protected by Copyright. Please refer to the COPYRIGHT file
 * distributed with this source distribution.
 *
 * This file is part of REDHAWK core.
 *
 * REDHAWK core is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * REDHAWK core is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see http://www.gnu.org/licenses/.
 */
// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#ifndef CXX___XML_XSD_PRF_PIMPL_H
#define CXX___XML_XSD_PRF_PIMPL_H

#include<memory>
#include "prf-pskel.h"
#include <ossie/logging/rh_logger.h>

namespace prf
{
    extern rh_logger::LoggerPtr parserLog;

    class Unit_pimpl: public virtual Unit_pskel,
      public ::xml_schema::string_pimpl
    {
      public:
      virtual void
      pre ();

      virtual std::string
      post_Unit ();
    };

    class AccessType_pimpl: public virtual AccessType_pskel,
      public ::xml_schema::string_pimpl
    {
      public:
      virtual void
      pre ();

      virtual ::ossie::Property::AccessType
      post_AccessType ();
    };

    class IsComplex_pimpl: public virtual IsComplex_pskel,
      public ::xml_schema::string_pimpl
    {
      public:
      virtual void
      pre ();

      virtual bool
      post_IsComplex ();
    };

    class IsCommandLine_pimpl: public virtual IsCommandLine_pskel,
      public ::xml_schema::string_pimpl
    {
      public:
      virtual void
      pre ();

      virtual bool
      post_IsCommandLine ();
    };
   
    class IsOptional_pimpl: public virtual IsOptional_pskel,
      public ::xml_schema::string_pimpl
    {
      public:
      virtual void
      pre ();

      virtual bool
      post_IsOptional ();
    };

    class action_pimpl: public virtual action_pskel
    {
      public:
      virtual void
      pre ();

      virtual void
      type (ossie::Property::ActionType);

      virtual ossie::Property::ActionType
      post_action ();
      private:
      ossie::Property::ActionType _type;
    };

    class ActionType_pimpl: public virtual ActionType_pskel,
      public ::xml_schema::string_pimpl
    {
      public:
      virtual void
      pre ();

      virtual ossie::Property::ActionType
      post_ActionType ();
    };

    class configurationKind_pimpl: public virtual configurationKind_pskel
    {
      public:
      virtual void
      pre ();

      virtual void
      kindtype (ossie::Property::KindType);

      virtual ossie::Property::KindType
      post_configurationKind ();

      private:
      ossie::Property::KindType _kindtype;
    };

    class enumeration_pimpl: public virtual enumeration_pskel
    {
      public:
      virtual void
      pre ();

      virtual void
      label (const ::std::string&);

      virtual void
      value (const ::std::string&);

      virtual ::std::map<std::string, std::string>::value_type
      post_enumeration ();
    };

    class enumerations_pimpl: public virtual enumerations_pskel
    {
      public:
      virtual void
      pre ();

      virtual void
      enumeration (const ::std::map<std::string, std::string>::value_type&);

      virtual ::std::map<std::string, std::string>
      post_enumerations ();
    };

    class inputValue_pimpl: public virtual inputValue_pskel
    {
      public:
      virtual void
      pre ();

      virtual void
      simple (const ossie::Property*);

      virtual void
      post_inputValue ();
    };

    class kind_pimpl: public virtual kind_pskel
    {
      public:
      virtual void
      pre ();

      virtual void
      kindtype (ossie::Property::KindType);

      virtual ossie::Property::KindType
      post_kind ();

      private:
      ossie::Property::KindType _type;
    };

    class PropertyConfigurationType_pimpl: public virtual PropertyConfigurationType_pskel,
      public ::xml_schema::string_pimpl
    {
      public:
      virtual void
      pre ();

      virtual ossie::Property::KindType
      post_PropertyConfigurationType ();
    };

    class StructPropertyConfigurationType_pimpl: public virtual StructPropertyConfigurationType_pskel,
      public PropertyConfigurationType_pimpl
    {
      public:
      virtual void
      pre ();

      virtual ossie::Property::KindType
      post_StructPropertyConfigurationType ();
    };

    class properties_pimpl: public properties_pskel
    {
      public:
      virtual void
      pre ();

      virtual void
      description (const ::std::string&);

      virtual void
      simple (ossie::SimpleProperty*);

      virtual void
      simplesequence (ossie::SimpleSequenceProperty*);

      virtual void
      test ();

      virtual void
      struct_ (ossie::StructProperty*);

      virtual void
      structsequence (ossie::StructSequenceProperty*);

      virtual std::unique_ptr<ossie::PRF>
      post_properties ();

      public:
      std::unique_ptr<ossie::PRF> _prf;
    };

    class PropertyValueType_pimpl: public virtual PropertyValueType_pskel,
      public ::xml_schema::string_pimpl
    {
      public:
      virtual void
      pre ();

      virtual std::string
      post_PropertyValueType ();
    };

    class range_pimpl: public virtual range_pskel
    {
      public:
      virtual void
      pre ();

      virtual void
      max (const ::std::string&);

      virtual void
      min (const ::std::string&);

      virtual ::std::pair<std::string, std::string>
      post_range ();

      private:
      std::pair<std::string, std::string> range;

    };

    class resultValue_pimpl: public virtual resultValue_pskel
    {
      public:
      virtual void
      pre ();

      virtual void
      simple (const ossie::Property*);

      virtual void
      post_resultValue ();
    };

    class simple_pimpl: public virtual simple_pskel
    {
      public:
      virtual void
      pre ();

      virtual void
      description (const ::std::string&);

      virtual void
      value (const ::std::string&);

      virtual void
      units ();

      virtual void
      range (const ::std::vector<std::string>&);

      virtual void
      enumerations (const ::std::map<std::string, std::string>&);

      virtual void
      kind (ossie::Property::KindType);

      virtual void
      action (ossie::Property::ActionType);

      virtual void
      id (const ::std::string&);

      virtual void
      mode (ossie::Property::AccessType);

      virtual void
      name (const ::std::string&);

      virtual void
      type (const ::std::string&);

      virtual void
      complex (bool);

      virtual void
      commandline (bool);

      virtual void
      optional (bool);

      virtual ossie::SimpleProperty*
      post_simple ();

      private:
      std::string _id;
      std::string _name;
      std::string _type;
      bool _complex;
      ossie::Property::AccessType _mode;
      ossie::Property::ActionType _action;
      bool _commandline;
      bool _optional;
      ossie::Property::Kinds _kinds;
      std::unique_ptr<std::string> _value;
    };

    class simpleRef_pimpl: public virtual simpleRef_pskel
    {
      public:
      virtual void
      pre ();

      virtual void
      refid (const ::std::string&);

      virtual void
      value (const ::std::string&);

      virtual const ossie::SimplePropertyRef&
      post_simpleRef ();

      private:
      ossie::SimplePropertyRef simple;
    };

    class simpleSequenceRef_pimpl: public virtual simpleSequenceRef_pskel
    {
      public:
      virtual void
      pre ();

      virtual void
      values (const ::std::vector<std::string>&);

      virtual void
      refid (const ::std::string&);

      virtual const ossie::SimpleSequencePropertyRef&
      post_simpleSequenceRef ();
    
      private:
      ossie::SimpleSequencePropertyRef simplesequence;
    };

    class simpleSequence_pimpl: public virtual simpleSequence_pskel
    {
      public:
      virtual void
      pre ();

      virtual void
      description (const ::std::string&);

      virtual void
      values (const ::std::vector<std::string>&);

      virtual void
      units ();

      virtual void
      range (const ::std::vector<std::string>&);

      virtual void
      kind (ossie::Property::KindType);

      virtual void
      action (ossie::Property::ActionType);

      virtual void
      id (const ::std::string&);

      virtual void
      mode (ossie::Property::AccessType);

      virtual void
      name (const ::std::string&);

      virtual void
      type (const ::std::string&);

      virtual void
      complex (bool);

      virtual void
      optional (bool);

      virtual ossie::SimpleSequenceProperty*
      post_simpleSequence ();

      private:
      std::string _id;
      std::string _name;
      std::string _type;
      bool _complex;
      ossie::Property::AccessType _mode;
      ossie::Property::ActionType _action;
      bool _optional;
      ossie::Property::Kinds _kinds;
      std::vector<std::string> _values;
    };

    class struct_pimpl: public virtual struct_pskel
    {
      public:
      virtual void
      pre ();

      virtual void
      description (const ::std::string&);

      virtual void
      simple (ossie::SimpleProperty*);

      virtual void
      simplesequence (ossie::SimpleSequenceProperty*);

      virtual void
      configurationkind (ossie::Property::KindType);

      virtual void
      id (const ::std::string&);

      virtual void
      mode (ossie::Property::AccessType);

      virtual void
      name (const ::std::string&);

      virtual ossie::StructProperty*
      post_struct ();

      private:
      std::string _id;
      std::string _name;
      ossie::Property::AccessType _mode;
      ossie::Property::Kinds _kinds;
      ossie::PropertyList _value;
    };

    class structSequence_pimpl: public virtual structSequence_pskel
    {
      public:
      virtual void
      pre ();

      virtual void
      struct_ (ossie::StructProperty*);

      virtual void
      description (const ::std::string&);

      virtual void
        structvalue (const ossie::ComponentPropertyMap&);

      virtual void
      configurationkind (ossie::Property::KindType);

      virtual void
      id (const ::std::string&);

      virtual void
      mode (ossie::Property::AccessType);

      virtual void
      name (const ::std::string&);

      virtual ossie::StructSequenceProperty*
      post_structSequence ();

      private:
      std::string _id;
      std::string _name;
      ossie::Property::AccessType _mode;
      ossie::Property::Kinds _kinds;
      std::unique_ptr<ossie::StructProperty> _struct;
      std::vector<ossie::StructProperty> _values;
    };

    class structValue_pimpl: public virtual structValue_pskel
    {
      public:
      virtual void
      pre ();

      virtual void
      simpleref (const ossie::SimplePropertyRef&);

      virtual void
      simplesequenceref (const ossie::SimpleSequencePropertyRef&);

      virtual const ossie::ComponentPropertyMap&
      post_structValue ();

      private:
      ossie::ComponentPropertyMap _values;
    };

    class test_pimpl: public virtual test_pskel
    {
      public:
      virtual void
      pre ();

      virtual void
      description (const ::std::string&);

      virtual void
      inputvalue ();

      virtual void
      resultvalue ();

      virtual void
      id (const ::std::string&);

      virtual void
      post_test ();
    };

    class values_pimpl: public virtual values_pskel
    {
      public:
      virtual void
      pre ();

      virtual void
      value (const ::std::string&);

      virtual ::std::vector<std::string>
      post_values ();
      private:
      std::vector<std::string> values;
    };
}
#endif // CXX___XML_XSD_PRF_PIMPL_H
