/*
 * This file is protected by Copyright. Please refer to the COPYRIGHT file
 * distributed with this source distribution.
 *
 * This file is part of REDHAWK core.
 *
 * REDHAWK core is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * REDHAWK core is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see http://www.gnu.org/licenses/.
 */
// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#ifndef CXX___XML_XSD_PROFILE_PIMPL_H
#define CXX___XML_XSD_PROFILE_PIMPL_H

#include "profile-pskel.h"

namespace profile
{
  class profile_pimpl: public profile_pskel
  {
    public:
    virtual void
    pre ();

    virtual void
    filename (const ::std::string&);

    virtual void
    type (const ::std::string&);

    virtual void
    post_profile ();
  };
}

#endif // CXX___XML_XSD_PROFILE_PIMPL_H
