/*
 * This file is protected by Copyright. Please refer to the COPYRIGHT file
 * distributed with this source distribution.
 *
 * This file is part of REDHAWK throughput.
 *
 * REDHAWK throughput is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * REDHAWK throughput is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see http://www.gnu.org/licenses/.
 */
module rawdata {
    typedef sequence<octet> octet_sequence;
    typedef sequence<short> short_sequence;
    typedef sequence<float> float_sequence;

    interface reader {
        void push_octet(in octet_sequence data);
        void push_short(in short_sequence data);
        void push_float(in float_sequence data);
        long long received();
        readonly attribute double average_time;
    };

    interface writer {
        void connect(in reader target, in string format);
        void transfer_length(in long length);
        void start();
        void stop();
        readonly attribute double average_time;
    };
};
