#!/bin/bash
# chkconfig: 2345 10 90
# description: Cleans omniNames on start


# Source function library.
. /etc/init.d/functions

#
# Setup service 
#

LOG_DIRS=/var/log/omniEvents:/var/lib/omniEvents:/var/log/omniNames:/var/log/omniORB::/var/lib/omniORB

start() 
{
    echo -e "Cleaning up OMNI log/cache directories..."
    for d in `echo $LOG_DIRS | tr ':' '\n' ` ;
    do
        #echo -e "Cleaning up $d ..."
        [ -d $d ] && rm -rf $d/* 2>/dev/null
    done
    rm -rf /tmp/omni-*          2>/dev/null
}

stop() 
{
	echo -e "Cleaning only done on start"
}

restart() 
{
	stop
	[ $? -eq 0 ] && start
	return $?
}

case "$1" in
	
	start)
		start $@
		;;
	stop)
		stop  $@
		;;
	restart)
		restart $@
		;;
	*)
		echo $"Usage: $0 {start|stop}"
		exit 1
esac

exit $?
