/*
 * This file is protected by Copyright. Please refer to the COPYRIGHT file 
 * distributed with this source distribution.
 * 
 * This file is part of REDHAWK core.
 * 
 * REDHAWK core is free software: you can redistribute it and/or modify it 
 * under the terms of the GNU Lesser General Public License as published by the 
 * Free Software Foundation, either version 3 of the License, or (at your 
 * option) any later version.
 * 
 * REDHAWK core is distributed in the hope that it will be useful, but WITHOUT 
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License 
 * for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License 
 * along with this program.  If not, see http://www.gnu.org/licenses/.
 */

#ifndef _DATASHM_IDL_
#define _DATASHM_IDL_

#include "ossie/BULKIO/bio_dataChar.idl"
#include "ossie/BULKIO/bio_dataDouble.idl"
#include "ossie/BULKIO/bio_dataFloat.idl"
#include "ossie/BULKIO/bio_dataLong.idl"
#include "ossie/BULKIO/bio_dataLongLong.idl"
#include "ossie/BULKIO/bio_dataOctet.idl"
#include "ossie/BULKIO/bio_dataShort.idl"
#include "ossie/BULKIO/bio_dataUlong.idl"
#include "ossie/BULKIO/bio_dataUlongLong.idl"
#include "ossie/BULKIO/bio_dataUshort.idl"

module BULKIO {

    exception NegotiationError {
       string msg;
    };

    interface NegotiableProvidesPort {
        void negotiate(in string protocol, in CF::Properties props) raises (NegotiationError);
    };

    interface dataCharExt : dataChar, NegotiableProvidesPort {
    };

    interface dataDoubleExt : dataDouble, NegotiableProvidesPort {
    };

    interface dataFloatExt : dataFloat, NegotiableProvidesPort {
    };

    interface dataLongExt : dataLong, NegotiableProvidesPort {
    };

    interface dataLongLongExt : dataLongLong, NegotiableProvidesPort {
    };

    interface dataOctetExt : dataOctet, NegotiableProvidesPort {
    };

    interface dataShortExt : dataShort, NegotiableProvidesPort {
    };

    interface dataUlongExt : dataUlong, NegotiableProvidesPort {
    };

    interface dataUlongLongExt : dataUlongLong, NegotiableProvidesPort {
    };

    interface dataUshortExt : dataUshort, NegotiableProvidesPort {
    };
};

#endif
