"""
The order of the files in `fpaths_ordered` determines how they will be
organized in the browser.
"""
fpaths_ordered = [
    'index.md',

    'getting-started/introduction.md',
    'getting-started/process-management.md',
    'getting-started/basic-sandbox-example.md',
    'getting-started/basic-ide-example.md',
    'getting-started/further-reading.md',

    'new/index.md',
    'new/custom-transport/add-transport.md',
    'new/gpp-plugins/using-gpp-plugins.md',
    'new/java-and-jacorb/java-and-jacorb-setup.md',
    'new/shared-address/components-howto.md',
    'new/shared-address/component-model.md',
    'new/shared-address/component-examples.md',
    'new/shared-memory/shared-memory-ipc.md',
    'new/shared-memory/metrics.md',
    'new/shared-memory/tuning.md',

    'installation/_index.md',
    'installation/redhawk-yum.md',
    'installation/dependencies.md',
    'installation/ide.md',
    'installation/source-install.md',
    'installation/troubleshooting.md',

    'components/components.md',
    'components/redhawk-core-assets.md',
    'components/creating-a-component.md',
    'components/octave-components.md',
    'components/running-a-component.md',
    'components/sandbox.md',
    'components/hello-world-component.md',

    'component-structure/_index.md',
    'component-structure/generated-files.md',
    'component-structure/generated-methods.md',
    'component-structure/base-component-members.md',
    'component-structure/component-implementations.md',
    'component-structure/java-version.md',
    'component-structure/manage-properties.md',
    'component-structure/events.md',

    'shared-libraries/_index.md',
    'shared-libraries/creating-a-shared-library-project.md',
    'shared-libraries/using-a-shared-library-project.md',
    'shared-libraries/packaging-shared-libraries.md',
    'shared-libraries/manually-including-external-libraries.md',

    'connections/_index.md',
    'connections/the-connection-process.md',
    'connections/why-ports.md',
    'connections/port-access.md',
    'connections/dynamic-connections.md',
    'connections/standardized-data-interfaces.md',

    'connections/bulkio/_index.md',
    'connections/bulkio/stream-api.md',
    'connections/bulkio/sri.md',
    'connections/bulkio/attachablestreams.md',
    'connections/bulkio/data-transfers.md',
    'connections/bulkio/bit-data.md',
    'connections/bulkio/multiout-ports.md',
    'connections/bulkio/working-with-complex-data.md',
    'connections/bulkio/time-stamps.md',
    'connections/bulkio/port-statistics.md',
    'connections/bulkio/examples.md',

    'connections/burstio/_index.md',
    'connections/burstio/data-transfers.md',
    'connections/burstio/sri.md',
    'connections/burstio/multiout-ports.md',
    'connections/burstio/working-with-complex-data.md',
    'connections/burstio/time-stamps.md',
    'connections/burstio/port-statistics.md',

    'connections/messaging/_index.md',
    'connections/messaging/message-producer.md',
    'connections/messaging/message-consumer.md',
    'connections/messaging/viewing-messages.md',
    'connections/messaging/connecting-producers-consumers.md',

    'connections/connection-callbacks.md',
    'connections/custom-idl-interfaces.md',

    'waveforms/_index.md',
    'waveforms/waveform-editor.md',
    'waveforms/sample-waveform.md',
    'waveforms/deployment-resources.md',

    'services/_index.md',

    'devices/_index.md',
    'devices/interacting-with-hardware/_index.md',
    'devices/interacting-with-hardware/creating-fei-device-ide.md',
    'devices/interacting-with-hardware/interacting-fei-device-python-package.md',
    'devices/interacting-with-hardware/using-fei-device-ide.md',
    'devices/associating-a-waveform.md',
    'devices/running-components.md',
    'devices/interface-with-fpgas.md',
    'devices/fei-data-structures.md',
    'devices/misc.md',

    'nodes/_index.md',
    'nodes/running-a-node.md',
    'nodes/creating-a-new-node.md',
    'nodes/distributed-computing-and-rf-devices.md',

    'sandbox/_index.md',
    'sandbox/python/_index.md',
    'sandbox/python/working_with_components.md',
    'sandbox/python/helpers.md',
    'sandbox/python/devices.md',
    'sandbox/python/example-interaction.md',
    'sandbox/python/sources-and-sinks.md',
    'sandbox/python/sdds-data.md',
    'sandbox/python/plotting-data.md',
    'sandbox/python/misc.md',
    'sandbox/ide/_index.md',

    'runtime-environment/_index.md',
    'runtime-environment/launching-a-domain.md',
    'runtime-environment/domain-manager.md',
    'runtime-environment/file-system.md',
    'runtime-environment/applications.md',
    'runtime-environment/application-factory.md',
    'runtime-environment/device-manager.md',
    'runtime-environment/allocation-manager.md',
    'runtime-environment/connection-manager.md',
    'runtime-environment/events.md',

    'runtime-inspection/_index.md',

    'logging/_index.md',
    'logging/logging-structure.md',
    'logging/configuring-logging-capabilities.md',
    'logging/adjusting-logging-at-runtime.md',
    'logging/logging-within-a-resource.md',
    'logging/viewing-logging-events.md',

    'ide/_index.md',
    'ide/launching-the-ide.md',
    'ide/pydev-overview.md',
    'ide/workbench.md',
    'ide/editors-and-views/_index.md',
    'ide/editors-and-views/softpkg-editor.md',
    'ide/editors-and-views/waveform-editor.md',
    'ide/editors-and-views/node-editor.md',
    'ide/editors-and-views/nextmidas-plot-editor.md',
    'ide/editors-and-views/redhawk-explorer-view.md',
    'ide/editors-and-views/redhawk-plot-view.md',
    'ide/editors-and-views/plot-settings-dialog.md',
    'ide/editors-and-views/event-viewer-view.md',
    'ide/editors-and-views/data-list-statistics-view.md',
    'ide/editors-and-views/port-monitor-view.md',
    'ide/editors-and-views/sri-view.md',
    'ide/editors-and-views/console-view.md',
    'ide/editors-and-views/properties-view.md',
    'ide/creating-redhawk-projects.md',
    'ide/namespaces.md',
    'ide/debugging.md',
    'ide/deploying-projects.md',
    'ide/snapshot-tool.md',
    'ide/connect-wizard.md',
    'ide/octave-wizard.md',
    'ide/plot-port-wizard.md',

    'exploring-sdrroot/_index.md',

    'sharing-projects/_index.md',

    'exploring-domain/_index.md',
    'exploring-domain/connecting-to-a-domain.md',
    'exploring-domain/viewing-domain-contents.md',
    'exploring-domain/working-with-waveforms.md',
    'exploring-domain/plotting-bulkio-ports.md',
    'exploring-domain/increasing-bulkio-connection-bandwidth.md',
    'exploring-domain/getting-error-condition-details.md',

    'appendices/_index.md',
    'appendices/optimization.md',
    'appendices/fei.md',
    'appendices/persona-device-pattern.md',
    'appendices/shared-memory.md',

    'appendices/troubleshooting/_index.md',
    'appendices/troubleshooting/omni.md',
    'appendices/troubleshooting/connections.md',
    'appendices/logging-config-plugin.md',

    'glossary.md',
    'acronyms.md',
]
