#!/bin/bash -x
#
# Runs relative to bulkio project
#

# can't use relative path for subdir's
# must get actual path so that subdir's use the correct path
bulkio_top=$(cd ../../../..;pwd)
bulkio_libsrc_top=$bulkio_top/libsrc
bulkio_libsrc_testdir=$bulkio_top/libsrc/testing/tests
export LD_LIBRARY_PATH=$bulkio_libsrc_top/.libs:$bulkio_top/.libs:$bulkio_top/jni/.libs:${LD_LIBRARY_PATH}
export PYTHONPATH=$bulkio_libsrc_top/python:$bulkio_libsrc_top/testing/helpers:${PYTHONPATH}
export CLASSPATH=${bulkio_libsrc_top}/bulkio.jar:${bulkio_top}/BULKIOInterfaces.jar:${CLASSPATH}

# Limit the number of threads Java uses for the garbage collector to avoid
# misleading Java "out of memory" errors that in all actuality  appear to be
# due to hitting the per-user process limit
export _JAVA_OPTIONS="-XX:ParallelGCThreads=1"


with_xunit=
pproc=
if [ $# -gt 0 ];
then
   if [ "-with-xunit" == "${1##[-+]}" ];
   then
       with_xunit="--with-xunit"
       shift
   fi
fi

#
# Run Python unit tests with XML output
#
# NOTE: virtualenv aliases python in the shell, so it's necessary to explicitly
# run runtests.py via python
./runtests.py  $*
